calibration:
  calibration_geography_id: zone_district_id
  proforma_cost_shifters:
    non_residential:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
    residential:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
