modelmanager_version: 0.1.dev15

saved_object:
    alt_capacity: job_spaces
    alt_filters: null
    alt_sample_size: 30
    alternatives: buildings
    choice_column: building_id
    chooser_filters:
    - sector_id == 9
    chooser_sample_size: null
    chooser_size: null
    choosers: jobs
    constrained_choices: true
    fitted_parameters:
    - 1.2631112798728
    - 4.744420811492362
    - 0.15165058296390588
    - -0.01275854685029297
    - 1.6693086547456877
    - -0.7774982038295641
    max_iter: null
    model_expression: ln_parcels_density_jobs + ln_blocks_prop_repm_id_industrial
        + ln_zones_median_non_residential_sqft + parcels_total_jobs_sum_2000_linear
        + ln_blocks_median_acres + parcels_sum_persons_ave_400_linear - 1
    name: elcm9
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters:
    - building_id == -1
    - sector_id == 9
    out_choosers: null
    out_column: building_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            248\nModel:\
        \         Multinomial Logit   Df Residuals:                242\nMethod:  \
        \     Maximum Likelihood   Df Model:                      6\nDate:       \
        \          2018-11-20   Pseudo R-squ.:             0.908\nTime:          \
        \            15:22   Pseudo R-bar-squ.:         0.901\nAIC:              \
        \       166.566   Log-Likelihood:          -77.283\nBIC:                 \
        \    187.647   LL-Null:                -843.497\n=========================================================================================\n\
        \                                          coef   std err         z     P>|z|\
        \   Conf. Int.\n-----------------------------------------------------------------------------------------\n\
        ln_parcels_density_jobs                 1.2631     0.280     4.509     0.000\
        \             \nln_blocks_prop_repm_id_industrial       4.7444     1.362 \
        \    3.483     0.000             \nln_zones_median_non_residential_sqft  \
        \  0.1517     0.107     1.423     0.155             \nparcels_total_jobs_sum_2000_linear\
        \     -0.0128     0.087    -0.147     0.883             \nln_blocks_median_acres\
        \                  1.6693     0.291     5.729     0.000             \nparcels_sum_persons_ave_400_linear\
        \     -0.7775     0.649    -1.199     0.231             \n========================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.1.dev15
