modelmanager_version: 0.1.dev15

saved_object:
    alt_capacity: job_spaces
    alt_filters: null
    alt_sample_size: 30
    alternatives: buildings
    choice_column: building_id
    chooser_filters:
    - sector_id == 6
    chooser_sample_size: 2000
    chooser_size: null
    choosers: jobs
    constrained_choices: true
    fitted_parameters:
    - 0.4768734950585141
    - 1.0420098942559488
    - 0.5180181548882534
    - 2.8579386174290037e-05
    - 2.498287533985073
    max_iter: null
    model_expression: ln_zones_total_jobs + ln_acres + ln_non_residential_sqft + zones_total_jobs_15_am_peak_travel_time
        + ln_zones_prop_building_type_id_4200 - 1
    name: elcm6
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters:
    - building_id == -1
    - sector_id == 6
    out_choosers: null
    out_column: building_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:          2,000\nModel:\
        \         Multinomial Logit   Df Residuals:              1,995\nMethod:  \
        \     Maximum Likelihood   Df Model:                      5\nDate:       \
        \          2018-11-20   Pseudo R-squ.:             0.855\nTime:          \
        \            15:22   Pseudo R-bar-squ.:         0.854\nAIC:              \
        \     1,979.505   Log-Likelihood:         -984.752\nBIC:                 \
        \  2,007.509   LL-Null:              -6,802.395\n============================================================================================\n\
        \                                             coef   std err         z   \
        \  P>|z|   Conf. Int.\n--------------------------------------------------------------------------------------------\n\
        ln_zones_total_jobs                        0.4769     0.059     8.142    \
        \ 0.000             \nln_acres                                   1.0420  \
        \   0.036    29.230     0.000             \nln_non_residential_sqft      \
        \              0.5180     0.016    32.271     0.000             \nzones_total_jobs_15_am_peak_travel_time\
        \    0.0000     0.000     8.865     0.000             \nln_zones_prop_building_type_id_4200\
        \        2.4983     0.406     6.149     0.000             \n============================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.1.dev15
