modelmanager_version: 0.1.dev15

saved_object:
    alt_capacity: job_spaces
    alt_filters: null
    alt_sample_size: 30
    alternatives: buildings
    choice_column: building_id
    chooser_filters:
    - sector_id == 1
    chooser_sample_size: null
    chooser_size: null
    choosers: jobs
    constrained_choices: true
    fitted_parameters:
    - 0.12358801866974416
    - 0.8925880514784287
    - 0.9294340831445662
    - -3.7235353502212285
    - -0.5653911227698859
    - -0.5056674570653339
    max_iter: null
    model_expression: ln_non_residential_sqft + ln_acres + ln_blocks_prop_repm_id_res_sf_detached
        + ln_blocks_prop_repm_id_duplex_townhome + ln_blocks_density_buildings + parcels_total_households
        - 1
    name: elcm1
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters:
    - building_id == -1
    - sector_id == 1
    out_choosers: null
    out_column: building_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:            725\nModel:\
        \         Multinomial Logit   Df Residuals:                719\nMethod:  \
        \     Maximum Likelihood   Df Model:                      6\nDate:       \
        \          2018-11-20   Pseudo R-squ.:             0.390\nTime:          \
        \            15:21   Pseudo R-bar-squ.:         0.388\nAIC:              \
        \     3,020.429   Log-Likelihood:       -1,504.214\nBIC:                 \
        \  3,047.946   LL-Null:              -2,465.868\n===========================================================================================\n\
        \                                            coef   std err         z    \
        \ P>|z|   Conf. Int.\n-------------------------------------------------------------------------------------------\n\
        ln_non_residential_sqft                   0.1236     0.012    10.625     0.000\
        \             \nln_acres                                  0.8926     0.046\
        \    19.382     0.000             \nln_blocks_prop_repm_id_res_sf_detached\
        \    0.9294     0.243     3.824     0.000             \nln_blocks_prop_repm_id_duplex_townhome\
        \   -3.7235     1.670    -2.230     0.026             \nln_blocks_density_buildings\
        \              -0.5654     0.098    -5.750     0.000             \nparcels_total_households\
        \                 -0.5057     0.099    -5.132     0.000             \n==========================================================================================="
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.1.dev15
