modelmanager_version: 0.1.dev15

saved_object:
    alt_capacity: job_spaces
    alt_filters: null
    alt_sample_size: 30
    alternatives: buildings
    choice_column: building_id
    chooser_filters:
    - sector_id == 15
    chooser_sample_size: null
    chooser_size: null
    choosers: jobs
    constrained_choices: true
    fitted_parameters:
    - 1.514919315177296
    - 0.154479257998246
    - -1.7171329801933273
    - 1.5942993046258658
    max_iter: null
    model_expression: ln_blocks_mean_acres + ln_blocks_mean_non_residential_sqft +
        locations_prop_building_type_id_1110 + ln_zones_sum_persons_15_am_peak_travel_time
        - 1
    name: elcm15
    out_alt_filters: null
    out_alternatives: null
    out_chooser_filters:
    - building_id == -1
    - sector_id == 15
    out_choosers: null
    out_column: building_id
    summary_table: "                  CHOICEMODELS ESTIMATION RESULTS            \
        \      \n===================================================================\n\
        Dep. Var.:                chosen   No. Observations:             18\nModel:\
        \         Multinomial Logit   Df Residuals:                 14\nMethod:  \
        \     Maximum Likelihood   Df Model:                      4\nDate:       \
        \          2018-11-20   Pseudo R-squ.:             0.339\nTime:          \
        \            15:23   Pseudo R-bar-squ.:         0.273\nAIC:              \
        \        88.959   Log-Likelihood:          -40.479\nBIC:                 \
        \     92.520   LL-Null:                 -61.222\n================================================================================================\n\
        \                                                 coef   std err         z\
        \     P>|z|   Conf. Int.\n------------------------------------------------------------------------------------------------\n\
        ln_blocks_mean_acres                           1.5149     0.359     4.222\
        \     0.000             \nln_blocks_mean_non_residential_sqft            0.1545\
        \     0.065     2.393     0.017             \nlocations_prop_building_type_id_1110\
        \          -1.7171     3.237    -0.530     0.596             \nln_zones_sum_persons_15_am_peak_travel_time\
        \    1.5943     0.233     6.851     0.000             \n================================================================================================"
    tags: []
    template: LargeMultinomialLogitStep
    template_version: 0.1.dev15
