output_variables:
    parcels:
        - total_households
        - total_jobs
        - sum_residential_units
        - sum_non_residential_sqft
        #- remaining_residential_unit_capacity
        #- remaining_nonresidential_sqft_capacity
        #- total_households_sum_2000_linear
        #- total_jobs_sum_2000_linear
        #- sum_residential_units_sum_2000_linear
        #- sum_non_residential_sqft_sum_2000_linear
        #- total_households_ave_2000_linear
        #- total_jobs_ave_2000_linear
        #- sum_residential_units_ave_2000_linear
        #- sum_non_residential_sqft_ave_2000_linear
        #- without_log_total_households_sum_2000_linear
        #- without_log_total_jobs_sum_2000_linear
        #- without_log_sum_residential_units_sum_2000_linear
        #- without_log_sum_non_residential_sqft_sum_2000_linear
        #- without_log_total_households_ave_2000_linear
        #- without_log_total_jobs_ave_2000_linear
        #- without_log_sum_residential_units_ave_2000_linear
        #- without_log_sum_non_residential_sqft_ave_2000_linear
        #- mean_income_ave_2000_linear
        #- without_log_mean_income_ave_2000_linear
        - mean_income
        - density_buildings
        - density_households
        - density_jobs


    zones:
        - total_households
        - total_jobs
        - sum_residential_units
        - sum_non_residential_sqft
#        - residential_vacancy_rate
#        - non_residential_vacancy_rate
#        - remaining_residential_unit_capacity
#        - remaining_nonresidential_sqft_capacity
        - mean_income
        - density_buildings
        - density_households
        - density_jobs
chart_data:
    geography_large: zone_district_id
    geography_small: block_id
    chart_variables:
        sum:
            - total_households
            - total_jobs
            - sum_residential_units
            - sum_non_residential_sqft
            - remaining_residential_unit_capacity
            - remaining_nonresidential_sqft_capacity
            - sum_job_spaces
        mean:
            - residential_vacancy_rate
            - non_residential_vacancy_rate
            - mean_value_per_unit
            - mean_income
    custom_charts:
        jobs:
            - sector_id
        households:
            - income_quartile
            - race_of_head
            - age_of_head_quartile
            - recent_mover_income
        buildings:
            - repm_id

